export const siteConfig = {
  name: "H.V Construction Pvt. Ltd.",
  shortName: "H.V Construction",
  tagline: "Building Tomorrow Together",
  secondaryTagline: "Building Infrastructure. Creating Spaces. Shaping the Future.",
  url: "https://hvconstruction.com",
  email: "info@hvconstruction.com",
  phone: "+91 78002 59225",
  secondaryPhone: "+91 81159 99307",
  contacts: [
    {
      name: "Mr. Anand Mishra",
      role: "Director / Executive Contact",
      phone: "+91 78002 59225",
      phoneClean: "917800259225",
      whatsapp: "https://wa.me/917800259225",
    },
    {
      name: "Mr. Sandeep Goswami",
      role: "Director / Executive Contact",
      phone: "+91 81159 99307",
      phoneClean: "918115999307",
      whatsapp: "https://wa.me/918115999307",
    },
  ],
  whatsapp: "https://wa.me/917800259225",
  instagram: "https://instagram.com",
  facebook: "https://facebook.com",
  linkedin: "https://linkedin.com",
  calendlyUrl: "",
  address: "House No. 1 Vedic Enclave, Near Amity University, Nijampur, Malhaur, Lucknow, Uttar Pradesh 226028",
  city: "Lucknow",
  state: "Uttar Pradesh",
  postalCode: "226028",
  responseTime: "Within 1 business day",
  pillars: [
    { label: "Quality Construction", desc: "Rigorous standards & premium materials" },
    { label: "Trust & Commitment", desc: "Transparent execution & lasting partnerships" },
    { label: "Stronger Infrastructure", desc: "Engineering designed for generations" },
    { label: "Safety First", desc: "Zero-compromise site & workplace safety" },
  ],
} as const;
